// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC0FwaXD6gOuETwFNA-dTBKXEzHUu1XCw',
    appId: '1:732239345656:web:e19ceebbe5e835dba8880d',
    messagingSenderId: '732239345656',
    projectId: 'weather-cup123',
    authDomain: 'weather-cup123.firebaseapp.com',
    storageBucket: 'weather-cup123.firebasestorage.app',
    measurementId: 'G-77PQF7TC2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_m1ALi0-OigXPtoeocP7kKC__vAvnE2I',
    appId: '1:732239345656:android:4c26e5c66cd9afc3a8880d',
    messagingSenderId: '732239345656',
    projectId: 'weather-cup123',
    storageBucket: 'weather-cup123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-gSinIyk98mSOdtm5zu4uXKZrLFVu9_Q',
    appId: '1:732239345656:ios:77a58796cd6df431a8880d',
    messagingSenderId: '732239345656',
    projectId: 'weather-cup123',
    storageBucket: 'weather-cup123.firebasestorage.app',
    iosBundleId: 'com.weathercup.weatherCup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-gSinIyk98mSOdtm5zu4uXKZrLFVu9_Q',
    appId: '1:732239345656:ios:77a58796cd6df431a8880d',
    messagingSenderId: '732239345656',
    projectId: 'weather-cup123',
    storageBucket: 'weather-cup123.firebasestorage.app',
    iosBundleId: 'com.weathercup.weatherCup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC0FwaXD6gOuETwFNA-dTBKXEzHUu1XCw',
    appId: '1:732239345656:web:b8d7be307b6fe3faa8880d',
    messagingSenderId: '732239345656',
    projectId: 'weather-cup123',
    authDomain: 'weather-cup123.firebaseapp.com',
    storageBucket: 'weather-cup123.firebasestorage.app',
    measurementId: 'G-QDCHNZS47H',
  );
}
